name: Run DeepSeek Workflow

on:
  schedule:
    - cron: "0 */6 * * *"  # Har 6 ghante mein chalega
  workflow_dispatch:       # Manual trigger bhi allow karega

permissions:
  contents: read

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install required Python modules
        run: |
          pip install telebot flask aiogram pyTelegramBotAPI python-telegram-bot psutil paramiko scp

      - name: Make all files executable
        run: |
          chmod +x *

      - name: Run broken.py
        run: |
          python3 broken.py
